server:
  port: 8080
  error:
    path: /error
  #SameSite Strict against CSRF Attacks
  servlet:
    session:
      cookie:
        same-site: Strict

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hackers_security
    username: veysel
    password: Haydibismillah
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      '[hibernate.format_sql]': true

logging:
  file:
    name: log/hackers_security.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]' : WARN
    '[org.hibernate]' : INFO
    '[com.hacker]' : DEBUG

hackers_security:
  app:
    jwtExpirationMs: 86400000

info:
  application:
    name: 'Hackers Security'
    description: 'This is a Hackers Security Project'
    version: '@project.version@'
